// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreData;

#nullable disable

namespace StoreManagement.Data.Migrations
{
    [DbContext(typeof(StoreManagementDbcontext))]
    [Migration("20240417101205_store")]
    partial class store
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamestoreManagement.Domain.Games", b =>
                {
                    b.Property<string>("GameTitle")
                        .HasColumnType("text");

                    b.Property<string>("GameDescription")
                        .HasColumnType("text");

                    b.HasKey("GameTitle");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GamestoreManagement.Domain.Joysticks", b =>
                {
                    b.Property<string>("JoyTitle")
                        .HasColumnType("text");

                    b.Property<string>("JoyDescription")
                        .HasColumnType("text");

                    b.HasKey("JoyTitle");

                    b.ToTable("Joysticks");
                });

            modelBuilder.Entity("GamestoreManagement.Domain.Login", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("username");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("GamestoreManagement.Domain.Players", b =>
                {
                    b.Property<string>("PlayerTitle")
                        .HasColumnType("text");

                    b.Property<string>("PlayerDescription")
                        .HasColumnType("text");

                    b.HasKey("PlayerTitle");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GamestoreManagement.Domain.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("MoblieNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Registers");
                });
#pragma warning restore 612, 618
        }
    }
}
